declare const Constants: {
    TAG: string;
    TASK_DETAIL_TAG: string;
    TASK_DETAIL_INFO_TAG: string;
    ANCHORS_INFO_TAG: string;
    DEPENDENCE_TAG: string;
    LOCK_TAG: string;
    NO_ANCHOR: string;
    HAS_ANCHOR: string;
    ANCHOR_RELEASE: string;
    START_METHOD: string;
    RUNNING_METHOD: string;
    FINISH_METHOD: string;
    RELEASE_METHOD: string;
    LINE_STRING_FORMAT: string;
    MS_UNIT: string;
    HALF_LINE_STRING: string;
    DEPENDENCIES: string;
    THREAD_INFO: string;
    START_TIME: string;
    START_UNTIL_RUNNING: string;
    RUNNING_CONSUME: string;
    FINISH_TIME: string;
    IS_ANCHOR: string;
    WRAPPED: string;
    YX_REPORT_KEY: string;
};
export default Constants;
